### ISSUE TITLE
Reproducible estimate files

### ISSUE THREAD

**Issue by bquistorff** [benjann/estwrite#2]
In some use-cases, one may want estimate files to be exactly the same after re-running the Stata code. Currently that's not the case with `estwrite` as it includes a timestamp (similar to other Stata data files), so even if the main content doesn't change, the file will. A few use-case examples would be:
- One may want to git version an estimates file (e.g., after a very time-consuming analysis) so that re-running would case needless/confusing git file changes.
- One may use a build-system to run a Stata project that looks at whether Stata script inputs have changed content for deciding whether to run the script. If an initial script re-generates the estimates file, it will be different causing the build system to needlessly re-run subsequent scripts that depend on that file. 

Would you support adding optional functionality to `estwrite` to support "reproducible" files that keep the file the same for multiple writes? If so, I'd be happy to submit a PR, but would like to know what user-experience you'd want to accept. A [common technique](https://reproducible-builds.org/docs/source-date-epoch/) to deal with timestamps in output, is to check for a common environment variable `SOURCE_DATE_EPOCH` and if it's set, to write a deterministic timestamp. Another idea (possibly in addition to the previous) is to have a parameter (probably optionally "on") to make it reproducible. Do you have any thoughts on the design?

Thanks

**Comment by benjann** [comment]
Hi Brian,
thanks for the comment. The `SOURCE_DATE_EPOCH` stuff appears complicated to me. How about just adding an option `notimestamp` to `estwrite`, so that the time stamp is omitted? `estread` doesn't do anything with the timestamp, so having the time stamp is kind of pointless anyhow.... Could also easily add an option `timestamp()` to allow the user to set a custom "time stamp" (could be any text, wouldn't necessarily have to be a time stamp).
ben

**Comment by bquistorff** [comment]
Thanks Ben, I'll work on a solution where users input a parameter.

Aside from the timestamps that you write, there are some that are written in the "Binary File Headers" that are written by `est save`/`__st_estimatessave_wrk()`. Do you know the file format of what they write so that I can parse them? If there's no easy way to parse it, I can try to search for the header text and replace the timestamps that way.

**Comment by benjann** [comment]
I don't know what `__st_estimatessave_wrk()` exactly does; it's code is not open. You'd have to ask Stata Corp for details. Maybe you could just look for all `*! Date ...` lines and modify them. (Possibly the details of the headers also depend on Stata version...)

An alternative is to use option `alt` when calling `estwrite`. In this case `__st_estimatessave_wrk()` is not used and the created file will only contain the header written by `estwrite`.

**Comment by benjann** [comment]
Option `reproducible` now added to main branch.
